name: Build problemset
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  problemset:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Read typesetting
        id: read-typesetting
        run: |
          pip install toml
          python3 .github/scripts/read_typesetting.py

      # For typst contests, run action directly in Ubuntu
      - if: steps.read-typesetting.outputs.typesetting == 'typst'
        run: |
          source .github/scripts/setup-ocimatic.sh
          ocimatic problemset

      # For latex contests, run action in container
      - uses: xu-cheng/texlive-action@v2
        if: steps.read-typesetting.outputs.typesetting == 'latex'
        with:
          scheme: debian
          run: |
            source .github/scripts/setup-ocimatic.sh
            ocimatic problemset

      # Move the generated pdf to a folder and deploy that folder to branch 'pdf'.
      - run: mkdir pdf
      - run: mv -t pdf/ oneside.pdf twoside.pdf
      - name: Deploy to branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: pdf
          FOLDER: pdf
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
