version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -e ".[dev]"
      - run:
          name: Check Formatting
          command: |
            . venv/bin/activate
            yapf --parallel --recursive --diff . || ( ! echo "Run yapf before committing (yapf -pri .)" )
