// This file contains the statement for a sample task used to demonstrate
// how to use Ocimatic. The other files generated by Ocimatic show how to
// generate test cases or write solutions using this task as an example.

// The template uses the "New Computer Modern Sans" font. This font is included in the
// "fonts" directory alongside this file. When compiling the statement with Ocimatic,
// it will automatically load the font. If you compile without Ocimatic, e.g., from
// the terminal or your editor, you have to manually load the font using the
// `--font-path` flag, for example:
//   typst compile --font-path fonts statement.typ
// Typst will also load fonts installed on your system, so installing the font is
// another option.
#import "oci.typ": *

#show: problem.with(
  title: "Suma de ejemplo",
)

#problemDescription[
  Este es un problema de ejemplo para mostrar cómo usar Ocimatic.
  El problema es muy simple.
  Te dan dos enteros y tienes que imprimir su suma.
  Pero ten cuidado ¡la suma podría no caber en un entero de 32 bits con signo!
]

#inputDescription[
  La entrada consiste en una sola línea con dos enteros $a$ y $b$ ($-3dot.op 10^9 <= a, b <= 3dot.op 10^9$).
]

#outputDescription[
  La salida debe contener un único entero correspondiente a la suma de $a$ y $b$.
]

#scoreDescription[
  #subtask(50)[
    Se probarán varios casos de prueba donde $-10^9 <= a, b <= 10^9$.
  ]

  #subtask(50)[
    Se probarán varios casos de prueba sin restricciones adicionales
  ]
]

#sampleDescription[
  #sampleIO("sample-1")
  #sampleIO("sample-2")
]
