[task]
# The task's codename. Java solutions must have a class using this
# name. The codename is included in the final pdf.
codename = "<filled by ocimatic when creating the task>"

# The priority is used to sort tasks in the final pdf. Specifically,
# tasks are sorted by first comparing the priority and then the codename.
priority = 0

[dataset]
# If true, test cases must be manually placed in the dataset directory.
# Additionally, commands that modify the dataset (e.g. `ocimatic testplan`)
# will be disabled for this task.
static = false
