name: Python

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1
      - name: Set up Python 3.10
        uses: actions/setup-python@v4.7.1
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
      - name: mypy
        run: |
          mypy .
      - name: ruff format
        run: |
          ruff format --check .

  integration-test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4.1.1

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install ocimatic
        run: pip install -e .

      - name: Test ocimatic
        run: |
          ocimatic init contest
          cd contest
          ocimatic new-task task
          cp ../tests/sample.java task/solutions/correct/
          ocimatic run-testplan
          ocimatic gen-expected
          ocimatic check-dataset
