name: Python

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1

      - name: Set up uv
        uses: astral-sh/setup-uv@v10.2.0

      - name: Install dependencies
        run: uv sync --locked

      - name: mypy
        run: uv run mypy .

      - name: pyright
        run: uv run pyright .

      - name: ruff
        run: |
          uv run ruff check
          uv run ruff format --check

  e2e-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4.1.1

      - name: Set up uv
        uses: astral-sh/setup-uv@v10.2.0

      - name: Install dependencies
        run: uv sync --locked

      - name: Run end-to-end tests
        run: uv run pytest -m e2e
